# Generated by Django 4.2.4 on 2023-08-12 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('extra_info', models.CharField(max_length=255)),
                ('status', models.CharField(default='accepted', max_length=15)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
