# Generated by Django 4.2.4 on 2023-08-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0002_alter_user_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
