# Generated by Django 4.2.4 on 2023-08-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0003_user_info_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='admin_note',
            field=models.CharField(default='ACK', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[('ACK', 'ACCEPTED'), ('REJ', 'REJECTED'), ('INP', 'IN PROGRESS'), ('COM', 'COMPLETED')], default='ACK', max_length=3),
        ),
    ]
