# Generated by Django 4.2.4 on 2023-08-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0004_user_info_admin_note_alter_user_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
