# Generated by Django 4.2.4 on 2023-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0006_alter_user_info_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='admin_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
