# Generated by Django 4.2.4 on 2023-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0009_rename_date_updated_user_info_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('IN-PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default='ACCEPTED', max_length=12),
        ),
    ]
