# Generated by Django 4.2.4 on 2023-08-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0010_alter_user_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='extra_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
